### ISSUE TITLE
Fix dark mode (colors, contrast, etc).

### ISSUE THREAD

**Issue by karol-depka** [InnoTopic/InnoTopic_Website#41]
(both dark and light mode should work, with a switcher that Alan implemented)

**Comment by karol-depka** [comment]
Alan's initial version:
https://github.com/InnoTopic/InnoTopic_Website/pull/40

Please familiarize Yourself and You can use this as a base.

**Comment by Zeioth** [comment]
#40 Ready to be reviewed/merged. Feel free to reopen.
